server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      server:
        git:
          uri: https://github.com/Get-Java/configs.git
          default-label: master
          clone-on-start: true
          force-pull: true
          username: aquadevv
          password: ${PASSWORD_GITHUB_TOKEN}
          search-paths: "{application}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/