server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      server:
        git:
          uri: https://github.com/Get-Java/configs.git
          default-label: master
          clone-on-start: true
          force-pull: true
          search-paths: "{application}"
        bootstrap: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8010/eureka}
  instance:
    preferIpAddress: true
