server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      server:
        git:
          uri: https://github.com/Get-Java/configs.git
          default-label: master
          clone-on-start: true
          force-pull: true
          search-paths:
            - "{application}"
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true
