server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      server:
        git:
          uri: https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/Get-Java/configs.git
          default-label: master
          clone-on-start: true
          force-pull: true
          search-paths: "{application}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/